import 'dart:convert';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:otp_crypto/pfs/errors.dart';

import '../server_identity.dart';

/// Signature helper for verifying server handshake signatures.
///
/// Goal:
/// - Verify Ed25519 signatures generated by Vault Transit.
///
/// Vault Transit "sign" typically returns the signature as base64 in one of
/// a few encodings depending on parameters:
/// - raw bytes (what we want)
/// - or a string that includes a prefix (e.g. "vault:v1:<b64>")
///
/// This helper accepts:
/// - raw signature bytes
/// - base64 signature string
/// - "vault:" prefixed signature string (it will strip prefix and decode tail)
final class PfsSignature {
  static final SignatureAlgorithm _ed25519 = Ed25519();

  /// Parse a Vault-style signature string into raw bytes.
  ///
  /// Accepted formats:
  /// - "<base64>"
  /// - "vault:v1:<base64>"
  /// - "vault:<anything>:<base64>" (takes substring after last ':')
  static Uint8List parseVaultSignature(String sig) {
    final s = sig.trim();
    if (s.isEmpty) throw PfsErrors.invalidInput('empty signature');

    // If it looks like a vault signature, take the tail after last colon.
    final idx = s.lastIndexOf(':');
    final b64 = (s.startsWith('vault:') && idx >= 0) ? s.substring(idx + 1) : s;

    try {
      return Uint8List.fromList(base64Decode(b64));
    } catch (_) {
      throw PfsErrors.invalidInput('invalid signature encoding');
    }
  }

  /// Verify signature over message bytes (typically transcript hash).
  ///
  /// - [message] is the bytes that were signed (e.g. 32-byte transcript hash).
  /// - [signatureBytes] is raw Ed25519 signature bytes.
  /// - [publicKey] must be Ed25519 public key.
  static Future<bool> verifyEd25519({
    required Uint8List message,
    required Uint8List signatureBytes,
    required SimplePublicKey publicKey,
  }) async {
    if (publicKey.type != KeyPairType.ed25519) {
      throw PfsErrors.invalidInput('publicKey must be Ed25519');
    }
    return _ed25519.verify(
      message,
      signature: Signature(signatureBytes, publicKey: publicKey),
    );
  }

  /// Verify with a [ServerIdentityKey] container.
  static Future<bool> verifyServerIdentity({
    required Uint8List message,
    required Uint8List signatureBytes,
    required ServerIdentityKey serverKey,
  }) async {
    switch (serverKey.ref.alg) {
      case ServerSigAlg.ed25519:
        return verifyEd25519(
          message: message,
          signatureBytes: signatureBytes,
          publicKey: serverKey.publicKey,
        );
    }
  }
}
